GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "content": "Banana",
    "date": "123321421",
    "important": false
}

